baseURL = 'https://pyrevitlabs.io/'
title = 'pyRevitLabs'
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
enableRobotsTXT = true

[markup.highlight]
style = "github-dark"

[params]
  author = "pyRevit"
  info = "RAD Tools for Autodesk Revit"
  description = "Rapid Application Development (RAD) Environment for Autodesk Revit"
  keywords = "pyRevit, pyrevitlabs, pyrevit labs, website"
  avatarurl = "pyRevitLogo.svg"

  since = 2014

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/pyrevitlabs/"
[[params.social]]
  name = "OpenCollective"
  icon = "fa-solid fa-circle-dollar-to-slot fa-2x"
  weight = 2
  url = "https://opencollective.com/pyrevitlabs/donate"
[[params.social]]
  name = "Forum pyRevit"
  icon = "fa-regular fa-comments fa-2x"
  weight = 3
  url = "https://discourse.pyrevitlabs.io"
[[params.social]]
  name = "Documentation"
  icon = "fa-solid fa-book fa-2x"
  weight = 4
  url = "http://wiki.pyrevitlabs.io/"
[[params.social]]
  name = "API Docs"
  icon = "fa-solid fa-code fa-2x"
  weight = 5
  url = "https://docs.pyrevitlabs.io/"
[[params.social]]
  name = "Developer Docs"
  icon = "fa-regular fa-keyboard fa-2x"
  weight = 6
  url = "http://devdocs.pyrevitlabs.io/"
[[params.social]]
  name = "pyRevit YouTube Channel"
  icon = "fa-brands fa-youtube fa-2x"
  weight = 7
  url = "https://www.youtube.com/@pyRevit"




# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about"
[[menu.main]]
  name = "Blog"
  weight = 2
  url  = "posts"
[[menu.main]]
  name = "Team"
  weight = 3
  url  = "team"
[[menu.main]]
  name = "Community Extensions"
  weight = 4
  url  = "extensions"
